networks:
  fleet_net:
    driver: bridge

volumes:
  registry_data:
  dev_docker_data:
  staging_docker_data:
  prod1_docker_data:
  prod2_docker_data:

services:
  registry:
    image: registry:2
    networks:
      - fleet_net
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

  traefik:
    image: traefik:v3.1
    command: ["--configFile=/etc/traefik/traefik.yml"]
    networks:
      - fleet_net
    ports:
      - "8081:80"
      - "8082:8080"
    volumes:
      - ./docker/loadbalancer/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  fleet-dev:
    build: docker/ssh-fleet
    hostname: dev
    privileged: true
    networks:
      fleet_net:
        aliases: [dev]
    ports:
      - "2201:22"
    volumes:
      - dev_docker_data:/var/lib/docker
      - ./secrets/ssh/id_ed25519.pub:/run/ssh-fleet/authorized_keys:ro

  fleet-staging:
    build: docker/ssh-fleet
    hostname: staging
    privileged: true
    networks:
      fleet_net:
        aliases: [staging]
    ports:
      - "2202:22"
    volumes:
      - staging_docker_data:/var/lib/docker
      - ./secrets/ssh/id_ed25519.pub:/run/ssh-fleet/authorized_keys:ro

  fleet-prod1:
    build: docker/ssh-fleet
    hostname: prod1
    privileged: true
    networks:
      fleet_net:
        aliases: [prod1]
    ports:
      - "2211:22"
    volumes:
      - prod1_docker_data:/var/lib/docker
      - ./secrets/ssh/id_ed25519.pub:/run/ssh-fleet/authorized_keys:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix(`/`)
      - traefik.http.services.app.loadbalancer.server.port=8080

  fleet-prod2:
    build: docker/ssh-fleet
    hostname: prod2
    privileged: true
    networks:
      fleet_net:
        aliases: [prod2]
    ports:
      - "2212:22"
    volumes:
      - prod2_docker_data:/var/lib/docker
      - ./secrets/ssh/id_ed25519.pub:/run/ssh-fleet/authorized_keys:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix(`/`)
      - traefik.http.services.app.loadbalancer.server.port=8080

  ansible-control:
    build: docker/ansible-control
    profiles: ["tools"]
    networks:
      - fleet_net
    environment:
      - ANSIBLE_VAULT_PASSWORD
      - HOME=/tmp
      - ANSIBLE_GALAXY_IGNORE_CERTS
    volumes:
      - ./ansible:/ansible
      - ./secrets/ssh/id_ed25519:/secrets/id_ed25519:ro
      - /var/run/docker.sock:/var/run/docker.sock
